name: Pre-release
on:
  push:
    branches: [pre-main]
permissions:
  contents: read
jobs:
  release:
    uses: leaflockio/core-actions/.github/workflows/tpl-release.yml@v1
    with:
      core-actions-ref: v1
      extra-plugins: "@semantic-release/exec"
    secrets:
      APP_ID: ${{ secrets.LOCKET_CI_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.LOCKET_CI_PRIVATE_KEY }}
